//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learner
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string ProfilePicURL { get; set; }
        public string SpeakLang1 { get; set; }
        public string SpeakLang2 { get; set; }
        public string SpeakLang3 { get; set; }
        public string LearnLang1 { get; set; }
        public string LearnLang2 { get; set; }
        public string LearnLang3 { get; set; }
        public string Comment { get; set; }
    }
}
